### ISSUE TITLE
Ubuntu cross compile for Windows instructions don't work on WSL

### ISSUE THREAD

**Issue by Hex27** [LMMS/lmms#7792]
### System Information

WSL, Ubuntu 20.04 (for building)

### LMMS Version(s)

f72ae32

### Bug Summary

The cross compile [instructions](https://github.com/LMMS/lmms/wiki/dependencies-windows#ubuntu-cross-compile) (compile on Ubuntu for Windows x64) seem to fail at the build step:
```
lmms/include/lmms_math.h:34:10: fatal error: numbers: No such file or directory
   34 | #include <numbers>
      |          ^~~~~~~~~
compilation terminated.
```

I'm new to building large projects, so I may be making a mistake somewhere, but I'm guessing that it's because the mingw installation recommended by the instructions fetches a mingw g++ version of `x86_64-w64-mingw32-g++ (GCC) 9.3-posix 20200320`, which doesn't have C++20 as needed by the repository.

Is there a simple fix on my end for this?

### Expected Behaviour

The project should cross compile on Ubuntu 20.04 with the given instructions

### Steps To Reproduce

-

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by messmerd** [comment]
Yeah, it looks like the build error is due to using MinGW 9 (GCC 9) which doesn't have support for C++20's `<numbers>` header.

We no longer use Ubuntu 20.04 for CI builds, so I would recommend upgrading to at least Ubuntu 22.04 if you can. Our MinGW CI uses [Ubuntu 24.04](https://github.com/LMMS/lmms/blob/master/.github/workflows/build.yml#L278). You'll need at least the equivalent of GCC 11 (*maybe* GCC 10) to build LMMS.

It looks like our ["Dependencies Windows"](https://github.com/LMMS/lmms/wiki/dependencies-windows) wiki page is out-of-date in that regard so I'll update it.

Note that due to the tobydox PPA dependencies being out-of-date, if you cross-compile your Windows build using the MinGW instructions, you won't have LV2 plugin support or MP3 sample support.

The alternative if you want up-to-date dependencies is a native Windows build using the [MSYS2 instructions](https://github.com/LMMS/lmms/wiki/Dependencies-Windows#windows-msys2) or the [MSVC instructions](https://github.com/LMMS/lmms/wiki/Dependencies-Windows#windows-msvc).

**Comment by Hex27** [comment]
Seems like the mingw from Ubuntu 22 (GCC 10) does indeed work, though the created package in NSIS was being really fussy with the path (it really doesn't like touching the Windows mount in WSL).

In the end I built it with
```
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin:/usr/lib/gcc/x86_64-w64-mingw32/10-posix:/usr/lib/gcc/i686-w64-mingw32/10-posix:/usr/x86_64-w64-mingw32/*:/usr/i686-w64-mingw32/*:/usr/share/nsis/* cmake --build build --target package 
```

Was that how NSIS is supposed to be used?

**Comment by messmerd** [comment]
> Was that how NSIS is supposed to be used?

I'm not sure, but @tresf might know

**Comment by tresf** [comment]
> the created package in NSIS was being really fussy with the path (it really doesn't like touching the Windows mount in WSL)

> ```bash
> PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin:/usr/lib/gcc/x86_64-w64-mingw32/10-posix:/usr/lib/gcc/i686-w64-mingw32/10-posix:/usr/x86_64-w64-mingw32/*:/usr/i686-w64-mingw32/*:/usr/share/nsis/* cmake --build build --target package 
> ```

If you know where your NSIS executable is, you can do:
```bash
cmake -DCPACK_NSIS_EXECUTABLE=/mingw64/bin/makensis.exe [... options ...]
```

What do you mean by "Windows mount"?  NSIS is an outlier to the mingw package prefixes because on Linux it uses the system-installed version.  I would expect WSL to find this the same as a native Ubuntu installation.  If you wanted to use the NSIS from an actual "Windows mount", then you'd have to set `CPACK_NSIS_EXECUTABLE` to something like `"/mnt/c/Program Files/NSIS/makensis.exe`, but the one from Ubuntu should suffice.  If cmake can't find it, maybe there's a symlink that's misplaced with the mixed environments?

**Comment by Hex27** [comment]
Ah, it was because I had some directories from my /mnt/c mount in my WSL $PATH. NSIS went into these directories and ran objdump on some dotnet binaries. That caused some hard errors that halted the CPack stage. 

I did find it kind of odd that NSIS would trawl for DLLs in $PATH instead of just exclusively picking the direct dependencies used by the repository, but I guess there's some weird edge case warranting that behaviour.

Anyway I did manage to build and run the latest commit so things should be okay for now, thanks for the help
