### ISSUE TITLE
Build error: BBTrackContainer.h

### ISSUE THREAD

**Issue by nggit** [LMMS/lmms#4713]
Hello. I build lmms 1.2 in gcc 4.6.3 and got these errors:

[  0%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/AutomationPattern.cpp.o
In file included from /home/xxx/lmms/src/core/AutomationPattern.cpp:34:0:
/home/xxx/lmms/include/BBTrackContainer.h:44:35: error: expected ';' at end of member declaration
/home/xxx/lmms/include/BBTrackContainer.h:44:37: error: 'override' does not name a type
/home/xxx/lmms/include/BBTrackContainer.h:46:36: error: expected ';' at end of member declaration
/home/xxx/lmms/include/BBTrackContainer.h:46:42: error: 'override' does not name a type
/home/tux/lmms/include/BBTrackContainer.h:65:65: error: expected ';' at end of member declaration
/home/tux/lmms/include/BBTrackContainer.h:65:71: error: 'override' does not name a type
src/CMakeFiles/lmmsobjs.dir/build.make:102: recipe for target 'src/CMakeFiles/lmmsobjs.dir/core/AutomationPattern.cpp.o' failed
make[2]: *** [src/CMakeFiles/lmmsobjs.dir/core/AutomationPattern.cpp.o] Error 1
CMakeFiles/Makefile2:340: recipe for target 'src/CMakeFiles/lmmsobjs.dir/all' failed
make[1]: *** [src/CMakeFiles/lmmsobjs.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by PhysSong** [comment]
I think it's introduced in #4046. GCC 4.6 doesn't fully support C++11, so could you consider upgrading your compiler? If you can't, you can remove the `override` keyword in `BBTrackContainer.h`.

**Comment by nggit** [comment]
OK. Thank you!

**Comment by zonkmachine** [comment]
As this seem resolved I'm closing the issue. Please reopen if I've closed this prematurely.
