### PR TITLE
Remove useless dependencies

### PR DESCRIPTION
**Pull request by jasp00**
Some objects depend on a library without using any of its symbols; this generates a useless dependency in packaged software. `RemoteZynAddSubFx` depended on libdl, libX11 and libXext. The vocoder LADSPA plugin depended on libfftw3f.

### CODE REVIEW

File: plugins/LadspaEffect/swh/CMakeLists.txt [hunk 1]
```diff
@@ -4,13 +4,16 @@ INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/include"
...
 FILE(GLOB PLUGIN_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.c")
 
 FOREACH(_item ${PLUGIN_SOURCES})
 	GET_FILENAME_COMPONENT(_plugin "${_item}" NAME_WE)
 
 	ADD_LIBRARY("${_plugin}" MODULE "${_item}")
+	# vocoder_1337 does not use fftw3f
+	IF(NOT ("${_plugin}" STREQUAL "vocoder_1337"))
+		TARGET_LINK_LIBRARIES("${_plugin}" -lfftw3f)
+	ENDIF()
```
Comment (tresf) [inline plugins/LadspaEffect/swh/CMakeLists.txt]: Good catch!  We can merge this, but it also needs to make it to https://github.com/swh/ladspa.  Many projects use Steve's upstream `swh` LADSPA packages and Steve's pretty good about merging in these types of PRs.

**Comment by jasp00** [comment]
Builds are fixed.
Should I help [bringing the vocoder into SWH](https://github.com/LMMS/lmms/issues/2366)?

**Comment by tresf** [comment]
@jasp00 sure if you think you can help.  I ran out of time working on it, but the build/xml file I was working on is available here if you think it helps: https://github.com/tresf/ladspa/blob/vocoder/vocoder_1337.xml

P.S. Sorry for delay on merging these.  The work you're doing is great and we desperately need the help, we're just very behind on things currently.

Off-topic to this particular PR but the `cmake` stuff specifically we don't have a bunch of people great at. (I'm pretty comfortable with writing `cmake`, but not as much with the linking and building portions as I'm not a C++ developer)

Anyway, thanks again. :+1:

**Comment by tresf** [comment]
👍

**Comment by midi-pascal** [comment]
@jasp00 @tresf The commit 60740fb breaks the build on my Ubuntu 14.04 x64 with this error:
``[ 78%] Generating moc_ZynAddSubFx.cxx``
``Generating embedded_resources.h``
``Linking CXX executable ../RemoteZynAddSubFx``
``Scanning dependencies of target zynaddsubfx``
``[100%] Built target lmmsobjs``
``[100%] [100%] Building CXX object plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/ZynAddSubFx.cpp.o``
``Scanning dependencies of target lmms``
``Building CXX object plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/moc_ZynAddSubFx.cxx.o``
``/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfltk.a(Fl_Double_Window.o): undefined reference to symbol 'XdbeAllocateBackBufferName'``
``//usr/lib/x86_64-linux-gnu/libXext.so.6: error adding symbols: DSO missing from command line``
``collect2: error: ld returned 1 exit status``
``make[2]: *** [plugins/RemoteZynAddSubFx] Error 1``
``make[1]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2``
``make[1]: *** Waiting for unfinished jobs....``
``[100%] Building CXX object src/CMakeFiles/lmms.dir/lmms_automoc.cpp.o``
``Building CXX object src/CMakeFiles/lmms.dir/core/main.cpp.o``
``Linking CXX executable ../lmms``
``[100%] Built target lmms``
``Linking CXX shared module ../libzynaddsubfx.so``
``[100%] Built target zynaddsubfx``
``make: *** [all] Error 2``

**Comment by jasp00** [comment]
> `/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfltk.a(Fl_Double_Window.o): undefined reference to symbol 'XdbeAllocateBackBufferName'`

Your build is using the static library `libfltk.a` rather than the shared one `libfltk.so`. I see that the package in Ubuntu does not depend on `libfltk1.3` (http://packages.ubuntu.com/trusty/lmms); this does not happen since wily.
What is the output of this command: `fltk-config --use-images --ldflags` ?

**Comment by midi-pascal** [comment]
@jasp00 
``fltk-config --use-images --ldflags``
``-Wl,-Bsymbolic-functions -lfltk_images -lfltk -lX11``

**Comment by midi-pascal** [comment]
@jasp00 Your fix solves the problem :+1:
