### ISSUE TITLE
zasfx preview noise while track playing

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2575]
To replicate:
 - open a new project
 - Punch in a couple of notes on the default kicker and press play
 - Press to preview zasfx->Arpeggios->Arpeggio1
 - Listen to the crackle/noise and see how it continues after the decay of the note if you keep the key pressed down. There is also distortion even if the track playing is muted.

I bisected this and came down to these four commits as possible suspects.

```
$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1864dcfaa1260e2659c85d1fb63cb2d428e9f1ab
1deb80acc38c4f42a5d7859a8251a9b09caed65a
857de8d2c829dc688745f41ba8eddbe148a63a20
9a3d3cb3064e38c22b60d092a32edef1959673b9
We cannot bisect more!
```

My bet is: 857de8d 

The ones I had to skip ( while bisecting ) because of failing to compile told me this:

```
... /lmms/src/core/FxMixer.cpp: In member function ‘virtual void FxChannel::doProcessing()’:
... /builds/lmms/src/core/FxMixer.cpp:173:50: error: ‘_buf’ was not declared in this scope
   m_stillRunning = m_fxChain.processAudioBuffer( _buf, fpp, m_hasInput );
                                                  ^
make[2]: *** [CMakeFiles/lmms.dir/src/core/FxMixer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/lmms.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by zonkmachine** [comment]
@Fastigium This might be an issue for you to take on... on a rainy day?

**Comment by tresf** [comment]
Likely unrelated, but reminds me a bit of #1644 since the arpeggio is involved. :beer:

**Comment by Fastigium** [comment]
This may very well be related to #2434. Note that I get some slight noise here while previewing Arpeggio1 even if no track is playing. It is a lot worse when a track is playing, though.

**Comment by Fastigium** [comment]
Good chance that this is fixed as well by #2586; testing welcome. I'm signing off for today, phew :sleeping:!

**Comment by zonkmachine** [comment]
Fixed! :beers: 
I stressed it good ( index finger is aching ) and nothing noisy happened that wasn't supposed to.

**Comment by Fastigium** [comment]
@zonkmachine Awesome! Thanks for testing!

**Comment by Fastigium** [comment]
This one can probably be closed now per the merging of #2586 :blush:

**Comment by Umcaruje** [comment]
@Fastigium When an issue is fixed, you can simply close it and cross reference it with the fix. Like this:

**Comment by Umcaruje** [comment]
Closed via #2586
